### ISSUE TITLE
Enterprise Image not working

### ISSUE THREAD

**Issue by MariusGrunenberg** [aborroy/alfresco-dockerx-builder#4]
### Noticed behavior

When trying to use Enterprise images, the repository somehow doesn't have the group "Alfresco" or the user "alfresco" anymore, which are normally used when using the official Docker images. 

That's why when starting it up, as used to  with Dockerfile containing:

```
RUN chown -R root:Alfresco ${TOMCAT_DIR}/webapps/alfresco ${TOMCAT_DIR}/amps ${TOMCAT_DIR}/lib ${TOMCAT_DIR}/shared/classes && \
    chmod -R u=rwX,g=rX,o= ${TOMCAT_DIR}/webapps/alfresco && \
    chmod -R u=rwX,g=rX,o= ${TOMCAT_DIR}/shared && \
    chmod -R u=rwX,g=rX,o= ${TOMCAT_DIR}/lib && \
    chmod 664 ${TOMCAT_DIR}/amps/*

    USER alfresco
```

I get multiple permission issues.

Also I noticed, when starting a standalone container with that generated image for enterprise, there are multiple ClassNotFoundExceptions, for example:

```Cannot load JDBC driver class 'org.gjt.mm.mysql.Driver'
java.lang.ClassNotFoundException: org.gjt.mm.mysql.Driver```

**Comment by aborroy** [comment]
Permissions has been fixed.

In relation with the `ClassNotFoundException`, that happens when using MySQL database. You need to add the JAR by yourself in your customized Docker Image.

Let me know if this works for you.

**Comment by MariusGrunenberg** [comment]
I am still getting a lot of errors, even when starting the image manually: 

`SEVERE [main] org.apache.catalina.startup.ContextConfig.beforeStart Exception fixing docBase for context [/api-explorer]
java.io.IOException: Unable to create the directory [/usr/local/tomcat/webapps/api-explorer]`


And also: 

`log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: alfresco.log (Permission denied)
log4j:ERROR Either File or DatePattern options are not set for appender [File].`

**Comment by aborroy** [comment]
May you attach some additional information on how are you using that?

It works for me on default Docker Compose templates provided (for instance) by https://github.com/AlfrescoLabs/alfresco-enterprise-docker

**Comment by aborroy** [comment]
I've applied some patches for these issues, let me know if that works as expected after that.

**Comment by MariusGrunenberg** [comment]
Ok looks better now, I can start Repo and Share without issues, however search-services seems to be faulty. So even when I use the Alfresco Enterprise Docker Generator, I get: 
```
alfresco-enterprise-docker-solr6-1               | Unrecognized VM option 'UseConcMarkSweepGC'
alfresco-enterprise-docker-solr6-1               | Error: Could not create the Java Virtual Machine.
alfresco-enterprise-docker-solr6-1               | Error: A fatal exception has occurred. Program will exit.
alfresco-enterprise-docker-solr6-1 exited with code 1
```

EDIT: I just looked on my old laptop, could it be that the JRE for the Search Services image is wrong? On my old laptop with a running search service I have 18.9 and the image used on the builder Dockerfile is 17.

**Comment by aborroy** [comment]
I need to address this properly. Search Services is still using Java 11, but it will be using Java 17 from 2.0.6. By now, this should be working.

**Comment by MariusGrunenberg** [comment]
Perfect, now it's working even with our Docker setup :). Will do some additional testing, but looks good so far!
